### ISSUE TITLE
reboot when trying to get the token from Samsung TV

### ISSUE THREAD

**Issue by ol65** [Toxblh/node-red-contrib-samsung-tv-control#131]
I see the following log:
Uncought Exception
Error: Error send key
at sendKey (/home/pi/.node-red/node_modules/samsung-tv-control/lib/samsung.js:55:23)
at WebSocket.ws.on (/home/pi/.node-red/node_modules/samsung-tv-control/lib/samsung.js:289:17)
at Websocket.emit (events.js:198:13)

**Comment by Just-another-pleb** [comment]
I may have a similar problem,
(Sorry not wanting to hi-jack your thread)
Mine came about when I was changing IP addresses.
It was working, I changed the IP address and it stopped.
So if you have done that try putting it back to the original IP address.
I am about to do that now with mine as I see I may not be the only one with this problem.
