### ISSUE TITLE
Crash on "GetToken" - or any other interaction with the TV

### ISSUE THREAD

**Issue by AndyPuettmann** [Toxblh/node-red-contrib-samsung-tv-control#6]
Hello there,
I am getting the following error message when trying to use the module:
```
20 Jan 22:45:07 - [red] Uncaught Exception:
20 Jan 22:45:07 - Error: RangeError: Invalid WebSocket frame: invalid status code 1005
    at sendKey (/home/pi/.node-red/node_modules/samsung-tv-control/lib/index.js:62:23)
    at WebSocket.ws.on (/home/pi/.node-red/node_modules/samsung-tv-control/lib/index.js:273:17)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Unit entered failed state.
nodered.service: Failed with result 'exit-code'.
nodered.service: Service hold-off time over, scheduling restart.
```
I am using a Raspberry-Pi 3 running node red.
TV in Question:

```
{
"device":
	{
	"FrameTVSupport":"false",
	"GamePadSupport":"true",
	"ImeSyncedSupport":"true",
	"Language":"de_DE",
	"OS":"Tizen",
	"PowerState":"on",
	"TokenAuthSupport":"true",
	"VoiceSupport":"false",
	"WallScreenRatio":"0",
	"WallService":"false",
	"countryCode":"DE",
	"description":"Samsung DTV RCR",
	"developerIP":"0.0.0.0",
	"developerMode":"0",
	"duid":"uuid:xxx",
	"firmwareVersion":"Unknown",
	"id":"uuid:xxx",
	"ip":"192.168.178.69",
	"model":"19_MUSEL_UHD_BASIC",
	"modelName":"UE65RU7179UXZG",
	"name":"[TV] Samsung 7 - Wohnzimmer",
	"networkType":"wired",
	"resolution":"3840x2160",
	"smartHubAgreement":"true",
	"type":"Samsung SmartTV",
	"udn":"uuid:xxx",
	"wifiMac":"<Ccopied to configuration node>"},
	"id":"uuid:xxx",
	"isSupport":"
		{
		\"DMP_DRM_PLAYREADY\":\"false\",
		\"DMP_DRM_WIDEVINE\":\"false\",
		\"DMP_available\":\"true\",
		\"EDEN_available\":\"true\",
		\"FrameTVSupport\":\"false\",
		\"ImeSyncedSupport\":\"true\",
		\"TokenAuthSupport\":\"true\",\
		"remote_available\":\"true\",
		\"remote_fourDirections\":\"true\",
		\"remote_touchPad\":\"true\",
		\"remote_voiceControl\":\"false\"
		}\n",
	"name":"[TV] Samsung 7 - Wohnzimmer",
	"remote":"1.0",
	"type":"Samsung SmartTV",
	"uri":"http://192.168.178.69:8001/api/v2/",
	"version":"2.0.25"
	}
```

node-red-contrib-samsung-tv-control version in use: 1.2.1

Node-Red completely restarts when trying to use any of the modules.

- Andy

**Comment by Toxblh** [comment]
Hello, could you also send to me getToken node? (Select->Menu->Export)

**Comment by AndyPuettmann** [comment]
`[{"id":"b427bca6.904ad","type":"samsung-tv-token","z":"ad485551.944d98","device":"bf8f60ec.ffea1","name":"TV-WZ-Get-Token","x":1800,"y":1360,"wires":[["8f3a7fc4.6d1ad"]]},{"id":"bf8f60ec.ffea1","type":"samsung-tv","z":"","name":"Wohnzimmer","model":"8001","ip":"192.168.178.69","mac":"d0:d0:03:d3:fe:55","token":""}]`

**Comment by Toxblh** [comment]
Ok,
1. Change your model to new, c'mon you have model 2017+!
2. And if doesn't help, pls send your version of `node -v`

**Comment by AndyPuettmann** [comment]
Interesting,
tried that many times before (even changed the IP of the TV) updated npm as well as all modules.
Restarted the raspberry pi a few times and reinstalled the nodes.

Nothing happened when using the 2017+ before, now it asked for permission and spit out the token in the debug node.

Sorry for the inconvenience seems like something on my network or pi had a malfunction before.

- Andy
