### ISSUE TITLE
Error getting Token and contrib crashes on websocket

### ISSUE THREAD

**Issue by stingone** [Toxblh/node-red-contrib-samsung-tv-control#96]
I have tried many ways to get a token. via the normal webbrowser directly to the ip of the TV a token is obtained. however via Node-red i get error below  and node-red crashes

27 Aug 22:20:02 - [red] Uncaught Exception:
27 Aug 22:20:02 - Error: Error send Key
    at /home/pi/.node-red/node_modules/samsung-tv-control/lib/samsung.js:55:23
    at WebSocket.<anonymous> (/home/pi/.node-red/node_modules/samsung-tv-control/lib/samsung.js:289:17)
    at WebSocket.emit (events.js:314:20)
    at Receiver.receiverOnError (/home/pi/.node-red/node_modules/ws/lib/websocket.js:951:13)
    at Receiver.emit (events.js:314:20)
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at onwriteError (_stream_writable.js:418:5)
    at onwrite (_stream_writable.js:445:5)
    at Receiver.startLoop (/home/pi/.node-red/node_modules/ws/lib/receiver.js:152:5)
    at Receiver._write (/home/pi/.node-red/node_modules/ws/lib/receiver.js:78:10)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Receiver.Writable.write (_stream_writable.js:318:11)
    at TLSSocket.socketOnData (/home/pi/.node-red/node_modules/ws/lib/websocket.js:1045:35)
    at TLSSocket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Failed with result 'exit-code'.

**Comment by stingone** [comment]
After lot of testing i found the "problem" seems that the Samsung TV does not allow connections from different subnets :( i use a lot of VLAN's. i have no setup node-red on same subnet as TV and it is now working.

**Comment by stingone** [comment]
Please update the contrib and give a proper error handeling without crashing Node-red when connecting on different subnets
